apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chain-node-rpc
  namespace: bohr-prod
  labels:
    app.kubernetes.io/name: chain-node-rpc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chain-node-rpc
  template:
    metadata:
      labels:
        app: chain-node-rpc
        app.kubernetes.io/name: chain-node-rpc
    spec:
      terminationGracePeriodSeconds: 30
      volumes:
        - name: node-config
          configMap:
            name: node-config
        - name: genesis-config
          configMap:
            name: genesis-config
      containers:
        - name: chain-node-rpc
          image: 630968570112.dkr.ecr.ap-northeast-1.amazonaws.com/bohr-prod/chain-node-rpc:mainnet-f0f429-20260215192940
          imagePullPolicy: Always
          command: [ "bash", "-x", "/data/chain/bin/scripts/node_archive_start.sh" ]
          ports:
            - containerPort: 30303
            - containerPort: 8545
            - containerPort: 8546
          # ============ 资源限制配置 ============
          resources:
            requests:
              memory: "100Mi"
              cpu: "10m"
              ephemeral-storage: "25Gi"
            limits:
              memory: "5000Mi"
              cpu: "2500m"
              ephemeral-storage: "30Gi"
          livenessProbe:
            failureThreshold: 10
            initialDelaySeconds: 600
            periodSeconds: 300
            successThreshold: 1
            tcpSocket:
              port: 8545
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 10
            initialDelaySeconds: 120
            periodSeconds: 300
            successThreshold: 1
            tcpSocket:
              port: 8545
            timeoutSeconds: 5
          env:
            - name: BASE_DIR
              value: "/data/app"
            - name: DATA_DIR
              value: "/data/app/node"
            - name: BIN_DIR
              value: "/data/chain/bin"
            - name: DB_ENGINE
              value: "pebble"
            - name: GC_MODE
              value: "archive"
            - name: STATE_SCHEME
              value: "hash"
            - name: SYNC_MODE
              value: "full"
            - name: PASSWORD
              value: "db4847e6338423"
            - name: HTTP_PORT
              value: "8545"
            - name: WS_PORT
              value: "8546"
            - name: P2P_PORT
              value: "30303"
            - name: METRICS_PORT
              value: "6060"
            - name: PPROF_PORT
              value: "7070"
            - name: HTTP_API
              value: "eth,net,web3,debug,txpool"
            - name: WS_API
              value: "eth,net,web3,debug,txpool"
            - name: TX_FEE_CAP # 允许通过 RPC 发送的单笔交易,最多可消耗的主币数量，作为手续费
              value: "1000"
            - name: PASSED_FORK_TIME
              value: "0"
            - name: LAST_HARDFORK_TIME # + 10
              value: "0"
            - name: RIALTO_HASH
              value: "0x721432edddc7ef9d94023659b6032e44692c9f87ac10d65be7423d0f80634f47"
            - name: BOOTNODES
              value: "enode://711644d33808b9b9734c1b8b9adb946e39960a0533f1afb68a6ff51890cf5d3c8a432e67db8846e6d5a80c99a6217f06546e4195386e9948245335e09ec066e4@18.179.76.29:30303,enode://104c42134a8bf8dc954e430e1e0e62aded74b4536156a44c1119a80757b8bc9368ba1cb8a4d3d3ed985b62f6626d75045d90282708b048aa4da4f4fd32aff97a@52.68.163.149:30303,enode://ce3dd55866f669d2f09016c27194cde5ae52624d7c7b6f0f8ee8ae2bdba027ac78a192ad449743371e15d12200c1d2ba16ec2ac6de2e88ccd1c6b2c3a1ab0b99@54.64.166.104:30303,enode://a7322debb3c33897d3c159f030a77c41bbd50360ba0eef872d81e89afc430e74c99936f4204f72e9c9e2caf0f800130c67f65e765d03638c7520e8113bd4977f@35.75.248.115:30303,enode://485e8259cebfe798137c59ef28ebe52dd8d52c26e59d88bfe3d772d7b97926571856935fe32f6dcd35eb4f0ee93533f783feb773933fead92cf204364074ca8b@18.176.87.178:30303,enode://34ea46f145cc0eb94763399490535ee553661ee9840bd66ddad2841e0f8e0eb6c52d23a6ae516eb90c1e1fa4a7d01f89c92eb94bdb256cad8e151083ec6a0884@35.73.218.11:30303,enode://f051f3ea3b13ec100a72ac381d096325d76cfa8529617b2040da2e896538ad439f6e3e8d299876854a47c63375be0ab44e509cb3151e04a8277aa7e77ab16c88@18.180.116.96:30303"

          volumeMounts:
            - name: genesis-config
              mountPath: /data/app/config-src/genesis.json
              subPath: genesis.json
            - name: node-config
              mountPath: /data/app/config-src/config.toml
              subPath: config.toml
            - name: rpc-data
              mountPath: /data/app/node

  volumeClaimTemplates:
    - metadata:
        name: rpc-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 500Gi
