apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scan-backend-stats-db-data-pvc
  namespace: bohr-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: "gp3"