apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scan-backend-logs-pvc
  namespace: bohr-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "gp3"