apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubo-pv
  labels:
    app.kubernetes.io/name: kubo
    app.kubernetes.io/managed-by: kubectl
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /tmp/kubo-data


